$j = jQuery.noConflict();
$j( document ).ready(function() {
    var eng = [
'Puzzles',
'and magic.',
'I work in what most people think',
'are two distinct fields,',
'but I believe they are the same.',
'I am both a magician and',
'a New York Times crossword puzzle constructor,',
'which basically means I\'ve taken',
'the world\'s two nerdiest hobbies',
'and combined them into one career.',
'And I believe that magic and puzzles are the same',
'because they both key into one of',
'the most important human drives:',
'the urge to solve.',
'Human beings are wired to solve,',
'to make order out of chaos.',
'It\'s certainly true for me.',
'I\'ve been solving my whole life.',
'High school consisted of epic Scrabble matches in the cafeteria',
'and not really talking to girls,',
'and then at about that time',
'I started learning magic tricks',
'and definitely not talking to girls.',
'There\'s nothing like starting a conversation with,',
'"Hey, did you know that \'prestidigitation\' is worth',
'20 points in Scrabble?"',
'But back then, I noticed an intersection',
'between puzzles and illusion.',
'When you do the crossword puzzle',
'or when you watch a magic show,',
'you become a solver,',
'and your goal is to try to find the order in the chaos,',
'the chaos of, say, a black-and-white puzzle grid,',
'a mixed-up bag of Scrabble tiles,',
'or a shuffled pack of playing cards.',
'And today, as a cruciverbalist —',
'23 points —',
'and an illusion designer, I create that chaos.',
'I test your ability to solve.',
'Now, it turns out research tells us',
'that solving is as primal as eating and sleeping.',
'From birth, we are wired to solve.',
'In one UCLA study, newborns still in the hospital',
'were shown patterns, patterns like this:',
'circle, cross, circle, cross.',
'And then the pattern was changed: triangle, square.',
'And by tracking an infant\'s gaze,',
'we know that newborns as young as a day old',
'can notice and respond to disruptions in order.',
'It\'s remarkable.',
'So from infancy through old age,',
'the urge to solve unites us all,',
'and I even found this photo on Instagram',
'of pop star Katy Perry solving a crossword puzzle',
'with her morning coffee.',
'Like.',
'(Laughter)',
'Now, solving exists across all cultures.',
'The American invention is the crossword puzzle,',
'and this year we are celebrating',
'the 100th anniversary of the crossword puzzle,',
'first published in The New York World.',
'But many other cultures have their signature puzzles as well.',
'China gives us tangrams,',
'which would test solvers\' abilities',
'to form shapes from the jumbled pieces.',
'Chaos. Order.',
'Order.',
'And order.',
'That one\'s my favorite, let\'s hear it again.',
'Okay.',
'And how about this puzzle',
'invented in 18th-century England:',
'the jigsaw puzzle.',
'Is this not making order out of chaos?',
'So as you can see,',
'we are always solving.',
'We are always trying to decode our world.',
'It\'s an eternal quest.',
'It\'s just like the one Cervantes wrote about',
'in "Don Quixote,"',
'which by the way is the root of the word "quixotry,"',
'the highest-scoring Scrabble word of all time,',
'365 points.',
'But anyway, "Don Quixote" is an important book.',
'You guys have read "Don Quixote," yes?',
'I\'m seeing some heads nod.',
'Come on guys, really?',
'Who\'s read "Don Quixote?" Let\'s do this. Raise your hands if you\'ve read "Don Quixote."',
'There we go. Smart audience.',
'Who\'s read "Don Quixote?" Get them up.',
'Okay, good, because I need somebody smart here',
'because now I\'m going to demonstrate',
'with the help of one of you',
'just how deeply rooted your urge to solve is,',
'just how wired to solve all of you really are,',
'so I\'m going to come into the audience',
'and find somebody to help me.',
'Let\'s see.',
'Everybody\'s looking away all of a sudden.',
'Can I? Would you? What is your name? Gwen.',
'I\'m not a mind reader, I can see your name tag.',
'Come with me, Gwen. Everyone give her a round of applause, make her feel welcome.',
'Gwen, after you.',
'(Applause)',
'Are you so excited?',
'Did you know that your name is worth',
'eight points in Scrabble?',
'Okay, stand right here, Gwen, right here.',
'Now, Gwen, before we begin,',
'I\'d like to point out a piece of the puzzle,',
'which is here in this envelope,',
'and I will not go near it. Okay?',
'And over here we have a drawing of some farm animals.',
'You can see we have an owl, we have a horse,',
'a donkey, a rooster, an ox, and a sheep,',
'and then here, Gwen, we have',
'some fancy art store markers,',
'colors like, can you see that word right there?',
'Gwen: Cobalt. David Kwong: Cobalt, yes. Cobalt.',
'But we have a silver, a red, an emerald,',
'and an amber marker,',
'and Gwen, you are going to color this drawing',
'just like you were five years old,',
'one marker at a time.',
'It\'s going to be a lot of fun.',
'But I\'m going to go over here.',
'I don\'t want to see what you\'re doing.',
'Okay, so don\'t start yet.',
'Wait for me to get over here and close my eyes.',
'Now Gwen, are you ready?',
'Pick up just one marker, pick up just one marker,',
'and why don\'t you color in the horse for me?',
'Color in the horse — big, big, big scribbles,',
'broad strokes, don\'t worry about staying in the lines.',
'All right. Great.',
'And why don\'t you take that marker and recap it',
'and place it on the table for me.',
'Okay, and pick up another marker out of the cup',
'and take off the cap',
'and color in the donkey for me, color in the donkey.',
'Big scribbles.',
'Okay, cool, and re-cap that marker',
'and place it on the table.',
'And pick up another marker for me',
'and take off the cap. Isn\'t this fun?',
'And color in the owl for me.',
'Color in the owl.',
'Okay, and recap that marker',
'and pick up another marker out of the cup',
'and color in the rooster for me, color in the rooster.',
'Good, good, good, good, good.',
'Big, big, big strokes. Good, good.',
'Pick up another marker out of the cup',
'and color in the ox for me. Color in the ox.',
'Okay, good.',
'A lot of color on that, and recap, and place it on the table,',
'and pick up another marker out of the cup.',
'Oh, I\'m out? Okay, I\'m going to turn around.',
'Did I forget? Oh, I forgot my purple marker.',
'This is still going to work, though.',
'I think this is still going to work, mostly.',
'So Gwen, I\'m going to hand you this envelope.',
'Don\'t open it yet. Do not open it yet,',
'but I am going to write down your choices',
'so that everybody can see',
'the choices that you made.',
'Okay, great. So we have a cobalt horse,',
'amber owl,',
'a silver ox,',
'yes, okay, a red donkey,',
'and what was the emerald color? A rooster.',
'An emerald rooster. Okay.',
'Now for the moment of truth, Gwen,',
'we\'re going to take a look in that envelope.',
'Why don\'t you open it up and remove',
'the one piece of paper from inside',
'and hand it to me,',
'and we will see if it matches your choices.',
'Yes, I think it does.',
'We have a cobalt horse, we have a red donkey,',
'we have an amber owl, we have an emerald rooster, a silver ox,',
'I forgot my purple marker so we have a blank sheep,',
'but that\'s a pretty amazing coincidence, don\'t you think?',
'Gwen, well done. That\'s beautiful. (Applause)',
'I\'ll take that back from you.',
'So ladies and gentlemen, how is this possible?',
'How is this possible? Well, could it be',
'that Gwen\'s brain is so wired to solve',
'that she decoded hidden messages?',
'Well this is the puzzle I present to you.',
'Could there be order',
'in the chaos that I created?',
'Let\'s take a closer look.',
'Do you recall when I showed you these puzzle pieces?',
'What image did it ultimately become? A cobalt horse.',
'The plot thickens.',
'And then we played a game of tangrams',
'with an emerald rooster.',
'That one\'s my favorite.',
'And then we had an experiment with a silver ox.',
'And Katy Perry drinks her morning coffee',
'out of an amber owl.',
'Thank you, Katy, for taking that photo for me.',
'Oh, and there\'s one more, there\'s one more.',
'I believe you colored a red donkey, Gwen.',
'Ladies and gentlemen, could you raise your hands',
'for me if you\'ve read "Don Quixote?"',
'Who\'s read "Don Quixote?" (Laughter)',
'But wait, but wait, wait, wait, wait, there\'s more.',
'There\'s more.',
'Gwen, I was so confident',
'that you were going to make these choices',
'that I made another prediction,',
'and I put it in an even more indelible place,',
'and it\'s right here.',
'Ladies and gentlemen,',
'we have today\'s New York Times.',
'The date is March 18th, 2014.',
'Many of you in the first couple of rows',
'have it underneath your seats as well.',
'Really dig. We hid them under there.',
'See if you can fish out the newspaper',
'and open up to the arts section',
'and you will find the crossword puzzle,',
'and the crossword puzzle today',
'was written by yours truly.',
'You can see my name above the grid.',
'I\'m going to give this to you, Gwen, to take a look.',
'And I will also put it up on the screen.',
'Now let\'s take a look',
'at another piece of the puzzle.',
'If you look at the first clue for 1-across,',
'it starts with the letter C, for corrupt,',
'and just below that we have an O, for outfielder,',
'and if you keep reading the first letters of the clues down,',
'you get cobalt horse,',
'amber owl, silver ox,',
'red donkey, and emerald rooster.',
'(Applause)',
'That\'s pretty cool, right?',
'It\'s The New York Times.',
'But wait, wait, wait, wait. Wait.',
'Oh, Gwen,',
'do you recall how I forgot my purple marker,',
'and you were unable to color the sheep?',
'Well, if you keep reading',
'starting with 25-down,',
'it says,',
'"Oh, by the way,',
'the sheep can be left blank."',
'(Laughter) (Applause)',
'But wait, wait, wait, there\'s one more thing,',
'there\'s one more thing,',
'there\'s one final piece of the puzzle.',
'Gwen, I am so grateful for your choices',
'because if we take a look',
'at the first letters of your combinations,',
'we get "C-H-A-O-S" for chaos',
'and "O-R-D-E-R" for order.',
'That\'s chaos and order.',
'We\'ve all made order out of chaos.',
'So ladies and gentlemen, the next time',
'you find yourself with a puzzle,',
'whether it\'s in your life or in your work,',
'or maybe it\'s at the Sunday morning',
'breakfast table with The New York Times,',
'remember, you are all wired to solve.',
'Thank you.',
'(Applause)'
];
	var rus = ['Головоломки',
'и иллюзионизм.',
'Я занимаюсь тем, что большинство людей считает',
'двумя отдельными областями,',
'но я считаю, что они очень схожи.',
'Я и иллюзионист',
'и составитель кроссвордов в «Нью-Йорк таймс»,',
'я, по сути, увлёкся',
'двумя хобби заядлых ботаников',
'и соединил их в одну карьеру.',
'Я считаю, что иллюзионизм и головоломки одинаковы по природе,',
'потому что они задевают',
'один из самых важных человеческих импульсов —',
'желание решать задачи.',
'Люди запрограммированы решать задачи,',
'приводить хаос в порядок.',
'Я-то — точно.',
'Я решаю задачи всю свою жизнь.',
'Старшие классы прошли, в эпических матчах в «Эрудит» в кафе,',
'а не с девочками,',
'и примерно в то же время',
'я стал учиться фокусам',
'и определённо не ухаживанию.',
'Ни с чем не сравнить, такое начало разговора:',
'«Слушай, а ты знала, что словом «престидижитация»',
'можно набрать 20 очков в «Эрудит»?»',
'Но тогда я заметил общее',
'между головоломками и иллюзионизмом.',
'Когда вы решаете кроссворд,',
'или когда смотрите фокусы,',
'вы начинаете решать задачу,',
'и вашей целью становится попытка, найти порядок в этом хаосе,',
'хаосе, скажем, черно-белой сетки кроссворда,',
'перемешанных букв в мешочке Эрудит',
'или перетасованной, колоде игральных карт.',
'И сегодня, как кроссвордист, —',
'23 очка —',
'и создатель иллюзий, я создаю хаос.',
'Я проверяю вашу способность, решать задачи.',
'Научные исследования показали,',
'что решение задач, так же первостепенно, как еда и сон.',
'С рождения мы запрограммированы решать задачи.',
'В одном из исследований Калифорнийского университета новорождённым в роддоме',
'показывали систематический набор образов, например,',
'круг, крест, круг, крест.',
'Потом его меняли: треугольник, квадрат.',
'И при исследовании взгляда ребёнка',
'выяснилось, что новорождённые уже в первый день жизни',
'могут замечать и реагировать на изменения в порядке.',
'Это поразительно.',
'С младенчества до самой старости',
'желание решать задачи объединяет нас всех,',
'я даже нашёл вот это фото в Инстаграм',
'поп-звезды Кэти Пэрри, где она решает кроссворд',
'за утренним кофе.',
'Мне нравится.',
'(Смех)',
'Задачи решают во всех культурах.',
'Кроссворд — американское изобретение,',
'и в этом году мы отмечаем',
'100-летие со дня публикации',
'первого кроссворда в газете The New York World.',
'Но и у многих других культур есть свои головоломки.',
'В Китае — танграмы,',
'которые проверяют умение',
'формировать образы, из разбросанных кусочков.',
'Хаос. Порядок.',
'Порядок.',
'И ещё раз порядок.',
'Этот — мой любимый, давайте ещё раз послушаем.',
'Хорошо.',
'Или как насчёт такой головоломки,',
'созданной в 18-м веке в Англии:',
'мозаика.',
'Не приведение ли это хаоса в порядок?',
'Так что, как видите,',
'мы всегда решаем задачи.',
'Мы постоянно пытаемся, расшифровать наш мир.',
'Это бесконечное приключение.',
'Такое же, о котором писал Сервантес',
'в «Дон Кихоте»,',
'кстати отсюда происходит слово, «донкихотство»,',
'самое ценное слово в Эрудит, за всю историю,',
'365 очков.',
'Как бы то ни было, «Дон Кихот» — важная книга.',
'Вы ведь читали «Дон Кихота»?',
'Вижу несколько кивков.',
'Серьёзно, ребят, ну правда?',
'Кто читал «Дон Кихота»? Давайте., Поднимите руки, кто читал.',
'Отлично. Умная аудитория.',
'Кто читал «Дон Кихота»? Поднимайте.',
'Хорошо, потому что мне нужен, кто-нибудь умный,',
'чтобы продемонстрировать',
'с помощью кого-нибудь из вас',
'насколько глубоко в нас находится, желание решать,',
'насколько вы все запрограммированы решать задачи,',
'поэтому я сейчас спущусь в зал',
'и найду себе помощника.',
'Посмотрим.',
'Все внезапно глядят в стороны.',
'Можно? Вы не могли бы? Как вас зовут? Гвен.',
'Я не читаю мысли, я вижу ваш пропуск.',
'Пойдёмте со мной, Гвен. Похлопайте ей, поприветствуйте её.',
'После вас, Гвен.',
'(Аплодисменты)',
'Вы взволнованы?',
'Вы знали, что ваше имя',
'принесёт 8 очков в Эрудит?',
'Хорошо, стойте здесь, Гвен, вот здесь.',
'Теперь, Гвен, прежде чем мы начнём,',
'я бы хотел обратить внимание, на часть головоломки',
'в этом конверте,',
'и я не буду к ней подходить. Хорошо?',
'А здесь у нас рисунки некоторых животных.',
'У нас тут сова, лошадь,',
'осёл, петух, бык и овца,',
'а вот здесь, Гвен,',
'у нас классные маркеры, из художественного салона,',
'такие цвета, как, вы можете видеть слово вот здесь?',
'Гвен: «Кобальт». Дэвид Квонг: «Кобальт, да».',
'Но у нас есть и серебряный, красный, изумрудный,',
'и янтарный маркеры,',
'и, Гвен, вы будете закрашивать эти картинки,',
'также, как когда вам было 5,',
'один маркер за раз.',
'Будет очень весело.',
'Я встану здесь.',
'И не буду смотреть, что вы делаете.',
'Хорошо, пока не начинайте.',
'Сейчас я закрою глаза.',
'Гвен, вы готовы?',
'Возьмите один маркер, возьмите только один маркер,',
'и закрасьте лошадь, пожалуйста.',
'Закрасьте лошадь большими чертами,',
'широкими штрихами, можете выходить за контуры.',
'Так. Прекрасно.',
'Наденьте на маркер крышечку',
'и положите его на стол.',
'Хорошо, теперь возьмите другой маркер,',
'снимите крышечку',
'и закрасьте осла.',
'Большими чертами.',
'Хорошо, здорово, наденьте крышку',
'и положите его на стол.',
'Теперь возьмите другой маркер',
'и снимите крышку. Весело, правда?',
'Закрасьте сову.',
'Закрасьте сову.',
'Хорошо, наденьте крышечку на маркер',
'и возьмите другой маркер из стакана',
'и закрасьте петуха.',
'Хорошо, хорошо.',
'Большими штрихами. Хорошо.',
'Возьмите другой маркер из стакана',
'и закрасьте быка. Закрасьте быка.',
'Хорошо.',
'Побольше краски, наденьте крышку, и положите на стол,',
'и возьмите другой маркер из стакана.',
'Ой, больше нет? Хорошо, я повернусь.',
'Я забыл?, Ой, я забыл свой фиолетовый маркер.',
'Но всё равно получится.',
'Думаю, всё равно получится, по большей части.',
'Итак, Гвен, я сейчас, дам вам этот конверт.',
'Не открывайте его пока. Не открывайте его пока,',
'я сейчас запишу, что вы выбрали,',
'чтобы все могли видеть',
'то, что вы выбрали.',
'Хорошо, прекрасно.,Итак, у нас кобальтовая лошадь,',
'янтарная сова,',
'серебряный бык,',
'да, так, красный осёл,',
'и кто был изумрудного цвета? Петух.',
'Изумрудный петух. Хорошо.',
'А теперь момент истины, Гвен,',
'мы сейчас увидим что в конверте.',
'Откройте его, достаньте',
'единственный лист бумаги,',
'дайте его мне',
'и мы увидим сходится ли он с вашим.',
'Да, думаю да.',
'Кобальтовая лошадь, красный осёл,',
'янтарная сова, изумрудный петух, серебряный бык,',
'я забыл фиолетовый маркер, так что овца белая,',
'но это довольно удивительное совпадение, не думаете?',
'Гвен, молодец. Прекрасно. (Аплодисменты)',
'Я это возьму себе.',
'И так, дамы и господа, как такое возможно?',
'Как такое возможно? Что ж,',
'может мозг Гвен, так запрограммирован решать задачи,',
'что она расшифровала скрытые сообщения?',
'Что ж, это головоломка вам от меня.',
'Может ли быть порядок',
'в хаосе, созданном мной?',
'Давайте посмотрим более детально.',
'Помните, когда я показал вам, эти кусочки мозаики?',
'Какую картинку они образовали?, Кобальтовую лошадь.',
'Интрига закручивается.',
'А потом мы играли в танграмы,',
'где был изумрудный петух.',
'Мой любимый.',
'А потом мы экспериментировали, с серебряным быком.',
'И Кэти Пэрри пила утренний кофе',
'из янтарной совы.',
'Спасибо, Кэти, за фото для меня.',
'Ах, и ещё кое-что, ещё кое-что.',
'Думаю, вы закрасили осла красным, Гвен.',
'Дамы и господа, поднимите руки,',
'если читали «Дон Кихота»?',
'Кто читал Дон Кихота? (Смех)',
'Но подождите, подождите, есть ещё кое-что.',
'Есть ещё кое-что.',
'Гвен, я был настолько уверен,',
'что вы сделаете именно так,',
'что я сделал ещё один прогноз,',
'и разместил его, в ещё более неизменном месте,',
'и он вот здесь.',
'Дамы и господа,',
'у нас сегодняшний выпуск New York Times.',
'Дата 18 марта 2014 года.',
'У многих в первых рядах',
'он под сиденьем.',
'Тянитесь. Мы спрятали их там.',
'Посмотрим, выловите ли вы газету.',
'Откройте секцию «искусство»',
'и вы найдёте кроссворд.',
'Сегодняшний кроссворд',
'составлен вашим покорным слугой.',
'Там моё имя над ним.',
'Сейчас я дам его вам, Гвен, посмотреть.',
'И я его также выведу на экран.',
'Теперь давайте посмотрим',
'на другой кусочек головоломки.',
'Посмотрите на определение, слова 1 по горизонтали,',
'оно начинается с буквы К,',
'а сразу под ней О,',
'и если продолжать читать, первые буквы определений,',
'получится кобальтовая лошадь,',
'янтарная сова, серебряный бык,',
'красный осёл и изумрудный петух.',
'(Аплодисменты)',
'Круто, правда?',
'В Нью-Йорк Таймс.',
'Но подождите!',
'Гвен,',
'вы помните, как я забыл, фиолетовый маркер?',
'И что вы не могли закрасить овцу?',
'Если продолжать читать,',
'начиная с 25 по вертикали,',
'там написано:',
'«Да, и кстати,',
'овцу можно не закрашивать».',
'(Смех) (Аплодисменты)',
'Но подождите, есть ещё кое-что,',
'есть ещё кое-что,',
'последний кусочек головоломки.',
'Гвен, я так благодарен вам, за выбор цветов,',
'потому что если мы посмотрим',
'на первые буквы ваших комбинаций,',
'мы увидим «Х-А-О-С»',
'и «П-О-Р-Я-Д-О-К».',
'Хаос и порядок.',
'Мы создали порядок из хаоса.',
'Дамы и господа, в следующий раз,',
'когда будете решать головоломку',
'в жизни или на работе,',
'или в воскресное утро',
'за завтраком, читая Нью-Йорк Таймс, помните,',
'что мы все запрограммированы, решать задачи.',
'Спасибо.',
'(Аплодисменты)',
];
	var i = 0;
	$j('#eng').text(eng[i]);
	$j('textarea').val(rus[i]);
	$j('#bt1').click(function(){
		if(i != 0) i -= 1;
		
		change(i);
	});
	$j('#bt2').click(function(){
		
		if(i != rus.length - 1) i += 1;
		change(i);
	});
	
	function change(i){
		$j('#num').text(i+1+"/"+eng.length);
		$j('#eng').text(eng[i]);
		$j('textarea').val(rus[i]);
		
	}
	
	function getCaret(el) { 
	  if (el.selectionStart) { 
		return el.selectionStart; 
	  } else if (document.selection) { 
		el.focus(); 
	 
		var r = document.selection.createRange(); 
		if (r == null) { 
		  return 0; 
		} 
	 
		var re = el.createTextRange(), 
			rc = re.duplicate(); 
		re.moveToBookmark(r.getBookmark()); 
		rc.setEndPoint('EndToStart', re); 
	 
		return rc.text.length; 
	  }  
	  return 0; 
	}
	
	$j(document).keypress(function(e) {
    if(e.which == 13) {
		var pos = getCaret(document.getElementById('rus'));
		console.log(pos);
		
		if($j('textarea').val() == ''){
			rus.splice(i,1);
		}else{
			rus[i] = $j('textarea').val();
			newString = rus[i].slice(pos);
			if(i==0 & pos==0){
				rus[i+1] = newString.concat(" ",rus[i+1]);
				rus.splice(i,1);
			} else if(i == rus.length - 1){
				rus.push(newString);
				rus[i] = rus[i].slice(0,pos);
			} else {
				rus[i+1] = newString.concat(" ",rus[i+1]);
				if(pos==0){
					rus.splice(i,1);
				}else{
					rus[i] = rus[i].slice(0,pos);
				}
			}
		}
		
		// 
		
		
		change(i);
		var out='';
		for(var x = 0; x < eng.length; x++){
			out += "{'en':'"+eng[x]+"','ru':'"+rus[x]+"'},";
		}
		$j('#output').text(out);
    }
	if(e.which == 40) {
		consol.log(1);
	
    }
	
	
	});
	
	
	});